/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/dashboard": {
    /** Get dashboard aggregate data */
    get: operations["getDashboard"];
  };
  "/media-managers": {
    /** List all configured media managers */
    get: operations["listMediaManagers"];
  };
  "/media-managers/{managerId}/status": {
    /** Get service health and stats */
    get: operations["getMediaManagerStatus"];
  };
  "/media-managers/{managerId}/queue": {
    /** Get download queue */
    get: operations["getMediaManagerQueue"];
  };
  "/media-managers/{managerId}/queue/{itemId}": {
    /** Clear item from queue */
    delete: operations["clearQueueItem"];
  };
  "/media-managers/{managerId}/stuck": {
    /** Get stuck queue items */
    get: operations["getStuckItems"];
    /** Clear all stuck items */
    delete: operations["clearStuckItems"];
  };
  "/media-managers/{managerId}/scan": {
    /** Trigger import scan */
    post: operations["triggerManagerScan"];
  };
  "/llm-providers": {
    /** List configured LLM providers */
    get: operations["listLLMProviders"];
  };
  "/llm-providers/{providerId}/status": {
    /** Get provider health and model */
    get: operations["getLLMProviderStatus"];
  };
  "/ai/settings": {
    /** Get current AI settings */
    get: operations["getAISettings"];
  };
  "/activity": {
    /** Get paginated activity log */
    get: operations["getActivity"];
  };
  "/activity/stream": {
    /** SSE stream for real-time activity */
    get: operations["activityStream"];
  };
  "/duplicates": {
    /** Get duplicate analysis */
    get: operations["getDuplicates"];
  };
  "/duplicates/{groupId}": {
    /** Delete inferior file from duplicate group */
    delete: operations["deleteDuplicate"];
  };
  "/scattered": {
    /** Get scattered media analysis */
    get: operations["getScattered"];
  };
  "/scattered/{itemId}/consolidate": {
    /** Consolidate scattered media item */
    post: operations["consolidateItem"];
  };
  "/scan": {
    /** Trigger library scan */
    post: operations["startScan"];
  };
  "/scan/status": {
    /** Get scan status */
    get: operations["getScanStatus"];
  };
  "/scan/stream": {
    /** SSE stream for scan progress */
    get: operations["scanStream"];
  };
  "/auth/status": {
    /** Check if auth is enabled and current state */
    get: operations["getAuthStatus"];
  };
  "/auth/login": {
    /** Authenticate with password */
    post: operations["login"];
  };
  "/auth/logout": {
    /** Clear session cookie */
    post: operations["logout"];
  };
  "/health": {
    /** Health check endpoint */
    get: operations["healthCheck"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    DashboardData: {
      libraryStats?: components["schemas"]["LibraryStats"];
      mediaManagers?: components["schemas"]["MediaManagerSummary"][];
      llmProvider?: components["schemas"]["LLMProviderSummary"];
      recentActivity?: components["schemas"]["ActivityEvent"][];
    };
    LibraryStats: {
      totalFiles?: number;
      /** Format: int64 */
      totalSize?: number;
      movieCount?: number;
      seriesCount?: number;
      episodeCount?: number;
      duplicateGroups?: number;
      /** Format: int64 */
      reclaimableBytes?: number;
      scatteredSeries?: number;
    };
    MediaManagerInfo: {
      id?: string;
      /** @enum {string} */
      type?: "sonarr" | "radarr" | "mediadownloader" | "custom";
      name?: string;
      enabled?: boolean;
      capabilities?: components["schemas"]["ManagerCapabilities"];
    };
    MediaManagerSummary: {
      id?: string;
      name?: string;
      type?: string;
      online?: boolean;
      queueSize?: number;
      stuckCount?: number;
    };
    ServiceStatus: {
      online?: boolean;
      version?: string;
      queueSize?: number;
      stuckCount?: number;
      error?: string;
    };
    ManagerCapabilities: {
      supportsRetry?: boolean;
      supportsPriority?: boolean;
      supportsHistory?: boolean;
      supportsQualityEdit?: boolean;
      supportsBulkActions?: boolean;
    };
    QueueItem: {
      /** Format: int64 */
      id?: number;
      title?: string;
      status?: string;
      progress?: number;
      /** Format: int64 */
      size?: number;
      /** Format: int64 */
      sizeRemaining?: number;
      timeLeft?: string;
      isStuck?: boolean;
      errorMessage?: string;
      downloadClient?: string;
    };
    LLMProviderInfo: {
      id?: string;
      /** @enum {string} */
      type?: "ollama" | "openai" | "anthropic" | "lmstudio" | "custom";
      name?: string;
      enabled?: boolean;
      currentModel?: string;
      capabilities?: components["schemas"]["LLMCapabilities"];
    };
    LLMProviderSummary: {
      id?: string;
      name?: string;
      online?: boolean;
      currentModel?: string;
    };
    LLMProviderStatus: {
      online?: boolean;
      model?: string;
      modelList?: components["schemas"]["LLMModel"][];
      error?: string;
    };
    LLMModel: {
      id?: string;
      name?: string;
      size?: string;
    };
    LLMCapabilities: {
      supportsStreaming?: boolean;
      supportsVision?: boolean;
      supportsModelSwitch?: boolean;
      localOnly?: boolean;
    };
    AISettings: {
      enabled?: boolean;
      defaultProvider?: string;
      confidenceThreshold?: number;
      autoApply?: boolean;
    };
    ActivityEvent: {
      id?: string;
      /** @enum {string} */
      type?: "FILE_DETECTED" | "FILE_ORGANIZED" | "DUPLICATE_FOUND" | "SYNC_COMPLETED" | "ERROR";
      message?: string;
      /** Format: date-time */
      timestamp?: string;
    };
    DuplicateAnalysis: {
      groups?: components["schemas"]["DuplicateGroup"][];
      totalFiles?: number;
      totalGroups?: number;
      /** Format: int64 */
      reclaimableBytes?: number;
    };
    DuplicateGroup: {
      id?: string;
      title?: string;
      year?: number;
      /** @enum {string} */
      mediaType?: "movie" | "series";
      files?: components["schemas"]["MediaFile"][];
      /** Format: int64 */
      bestFileId?: number;
      /** Format: int64 */
      reclaimableBytes?: number;
    };
    MediaFile: {
      /** Format: int64 */
      id?: number;
      path?: string;
      /** Format: int64 */
      size?: number;
      resolution?: string;
      sourceType?: string;
      qualityScore?: number;
    };
    ScatteredAnalysis: {
      items?: components["schemas"]["ScatteredItem"][];
      totalItems?: number;
      totalMoves?: number;
      /** Format: int64 */
      totalBytes?: number;
    };
    ScatteredItem: {
      /** Format: int64 */
      id?: number;
      title?: string;
      year?: number;
      mediaType?: string;
      locations?: string[];
      targetLocation?: string;
      filesToMove?: number;
      /** Format: int64 */
      bytesToMove?: number;
    };
    ConsolidationResult: {
      success?: boolean;
      filesMoved?: number;
      /** Format: int64 */
      bytesMoved?: number;
      errors?: string[];
    };
    ScanStatus: {
      /** @enum {string} */
      status?: "idle" | "scanning" | "completed" | "failed";
      progress?: number;
      message?: string;
    };
    AuthStatus: {
      enabled?: boolean;
      authenticated?: boolean;
    };
    OperationResult: {
      success?: boolean;
      message?: string;
      filesAffected?: number;
      /** Format: int64 */
      bytesAffected?: number;
    };
    Error: {
      code?: string;
      message?: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get dashboard aggregate data */
  getDashboard: {
    responses: {
      /** @description Dashboard data */
      200: {
        content: {
          "application/json": components["schemas"]["DashboardData"];
        };
      };
    };
  };
  /** List all configured media managers */
  listMediaManagers: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MediaManagerInfo"][];
        };
      };
    };
  };
  /** Get service health and stats */
  getMediaManagerStatus: {
    parameters: {
      path: {
        managerId: string;
      };
    };
    responses: {
      /** @description Manager status */
      200: {
        content: {
          "application/json": components["schemas"]["ServiceStatus"];
        };
      };
    };
  };
  /** Get download queue */
  getMediaManagerQueue: {
    parameters: {
      query?: {
        limit?: number;
      };
      path: {
        managerId: string;
      };
    };
    responses: {
      /** @description Queue items */
      200: {
        content: {
          "application/json": components["schemas"]["QueueItem"][];
        };
      };
    };
  };
  /** Clear item from queue */
  clearQueueItem: {
    parameters: {
      query?: {
        blocklist?: boolean;
      };
      path: {
        managerId: string;
        itemId: number;
      };
    };
    responses: {
      /** @description Item cleared */
      200: {
        content: {
          "application/json": components["schemas"]["OperationResult"];
        };
      };
    };
  };
  /** Get stuck queue items */
  getStuckItems: {
    parameters: {
      path: {
        managerId: string;
      };
    };
    responses: {
      /** @description Stuck items */
      200: {
        content: {
          "application/json": components["schemas"]["QueueItem"][];
        };
      };
    };
  };
  /** Clear all stuck items */
  clearStuckItems: {
    parameters: {
      query?: {
        blocklist?: boolean;
      };
      path: {
        managerId: string;
      };
    };
    responses: {
      /** @description Items cleared */
      200: {
        content: {
          "application/json": components["schemas"]["OperationResult"];
        };
      };
    };
  };
  /** Trigger import scan */
  triggerManagerScan: {
    parameters: {
      path: {
        managerId: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          path?: string;
        };
      };
    };
    responses: {
      /** @description Scan triggered */
      202: {
        content: {
          "application/json": components["schemas"]["OperationResult"];
        };
      };
    };
  };
  /** List configured LLM providers */
  listLLMProviders: {
    responses: {
      /** @description List of providers */
      200: {
        content: {
          "application/json": components["schemas"]["LLMProviderInfo"][];
        };
      };
    };
  };
  /** Get provider health and model */
  getLLMProviderStatus: {
    parameters: {
      path: {
        providerId: string;
      };
    };
    responses: {
      /** @description Provider status */
      200: {
        content: {
          "application/json": components["schemas"]["LLMProviderStatus"];
        };
      };
    };
  };
  /** Get current AI settings */
  getAISettings: {
    responses: {
      /** @description AI settings */
      200: {
        content: {
          "application/json": components["schemas"]["AISettings"];
        };
      };
    };
  };
  /** Get paginated activity log */
  getActivity: {
    parameters: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      /** @description Activity events */
      200: {
        content: {
          "application/json": {
            events?: components["schemas"]["ActivityEvent"][];
          };
        };
      };
    };
  };
  /** SSE stream for real-time activity */
  activityStream: {
    responses: {
      /** @description Server-Sent Events stream */
      200: {
        content: {
          "text/event-stream": string;
        };
      };
    };
  };
  /** Get duplicate analysis */
  getDuplicates: {
    responses: {
      /** @description Duplicate analysis */
      200: {
        content: {
          "application/json": components["schemas"]["DuplicateAnalysis"];
        };
      };
    };
  };
  /** Delete inferior file from duplicate group */
  deleteDuplicate: {
    parameters: {
      query?: {
        fileId?: number;
      };
      path: {
        groupId: string;
      };
    };
    responses: {
      /** @description File deleted */
      200: {
        content: {
          "application/json": components["schemas"]["OperationResult"];
        };
      };
    };
  };
  /** Get scattered media analysis */
  getScattered: {
    responses: {
      /** @description Scattered analysis */
      200: {
        content: {
          "application/json": components["schemas"]["ScatteredAnalysis"];
        };
      };
    };
  };
  /** Consolidate scattered media item */
  consolidateItem: {
    parameters: {
      path: {
        itemId: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          /** @default false */
          dryRun?: boolean;
        };
      };
    };
    responses: {
      /** @description Consolidation result */
      200: {
        content: {
          "application/json": components["schemas"]["ConsolidationResult"];
        };
      };
    };
  };
  /** Trigger library scan */
  startScan: {
    responses: {
      /** @description Scan started */
      202: {
        content: {
          "application/json": components["schemas"]["ScanStatus"];
        };
      };
    };
  };
  /** Get scan status */
  getScanStatus: {
    responses: {
      /** @description Scan status */
      200: {
        content: {
          "application/json": components["schemas"]["ScanStatus"];
        };
      };
    };
  };
  /** SSE stream for scan progress */
  scanStream: {
    responses: {
      /** @description Server-Sent Events stream */
      200: {
        content: {
          "text/event-stream": string;
        };
      };
    };
  };
  /** Check if auth is enabled and current state */
  getAuthStatus: {
    responses: {
      /** @description Auth status */
      200: {
        content: {
          "application/json": components["schemas"]["AuthStatus"];
        };
      };
    };
  };
  /** Authenticate with password */
  login: {
    requestBody?: {
      content: {
        "application/json": {
          password: string;
        };
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        content: never;
      };
      /** @description Invalid password */
      401: {
        content: never;
      };
    };
  };
  /** Clear session cookie */
  logout: {
    responses: {
      /** @description Logged out */
      200: {
        content: never;
      };
    };
  };
  /** Health check endpoint */
  healthCheck: {
    responses: {
      /** @description Service is healthy */
      200: {
        content: {
          "application/json": {
            status?: string;
            version?: string;
          };
        };
      };
    };
  };
}
