/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/dashboard": {
    /** Get dashboard aggregate data */
    get: operations["getDashboard"];
  };
  "/media-managers": {
    /** List all configured media managers */
    get: operations["listMediaManagers"];
  };
  "/media-managers/{managerId}/status": {
    /** Get service health and stats */
    get: operations["getMediaManagerStatus"];
  };
  "/media-managers/{managerId}/queue": {
    /** Get download queue */
    get: operations["getMediaManagerQueue"];
  };
  "/media-managers/{managerId}/queue/{itemId}": {
    /** Clear item from queue */
    delete: operations["clearQueueItem"];
  };
  "/media-managers/{managerId}/stuck": {
    /** Get stuck queue items */
    get: operations["getStuckItems"];
    /** Clear all stuck items */
    delete: operations["clearStuckItems"];
  };
  "/media-managers/{managerId}/scan": {
    /** Trigger import scan */
    post: operations["triggerManagerScan"];
  };
  "/llm-providers": {
    /** List configured LLM providers */
    get: operations["listLLMProviders"];
  };
  "/llm-providers/{providerId}/status": {
    /** Get provider health and model */
    get: operations["getLLMProviderStatus"];
  };
  "/ai/settings": {
    /** Get current AI settings */
    get: operations["getAISettings"];
  };
  "/activity": {
    /** Get paginated activity log */
    get: operations["getActivity"];
  };
  "/activity/stream": {
    /** SSE stream for real-time activity */
    get: operations["activityStream"];
  };
  "/duplicates": {
    /** Get duplicate analysis */
    get: operations["getDuplicates"];
  };
  "/duplicates/{groupId}": {
    /** Delete inferior file from duplicate group */
    delete: operations["deleteDuplicate"];
  };
  "/scattered": {
    /** Get scattered media analysis */
    get: operations["getScattered"];
  };
  "/scattered/{itemId}/consolidate": {
    /** Consolidate scattered media item */
    post: operations["consolidateItem"];
  };
  "/scan": {
    /** Trigger library scan */
    post: operations["startScan"];
  };
  "/scan/status": {
    /** Get scan status */
    get: operations["getScanStatus"];
  };
  "/scan/stream": {
    /** SSE stream for scan progress */
    get: operations["scanStream"];
  };
  "/auth/status": {
    /** Check if auth is enabled and current state */
    get: operations["getAuthStatus"];
  };
  "/auth/login": {
    /** Authenticate with password */
    post: operations["login"];
  };
  "/auth/logout": {
    /** Clear session cookie */
    post: operations["logout"];
  };
  "/jellyfin/verify": {
    /** Get Jellyfin verification status */
    get: operations["getJellyfinVerification"];
  };
  "/jellyfin/verify/run": {
    /** Run Jellyfin verification for a library */
    post: operations["runJellyfinVerification"];
  };
  "/jellyfin/verify/results": {
    /** Get verification results */
    get: operations["getJellyfinVerificationResults"];
  };
  "/jellyfin/unidentifiable": {
    /** Get unidentifiable items from Jellyfin */
    get: operations["getJellyfinUnidentifiableItems"];
  };
  "/jellyfin/plugin/status": {
    /** Get JellyWatch companion plugin status */
    get: operations["getJellyfinPluginStatus"];
  };
  "/health": {
    /** Health check endpoint */
    get: operations["healthCheck"];
  };
  "/webhooks/jellyfin": {
    /** Receive Jellyfin webhook events */
    post: operations["jellyfinWebhook"];
  };
  "/settings/{section}": {
    /** Read a config section */
    get: operations["getSettingsSection"];
    /** Replace a config section */
    put: operations["putSettingsSection"];
  };
  "/settings/paths/{kind}": {
    /** List watch paths */
    get: operations["getSettingsPaths"];
    /** Replace watch paths */
    put: operations["replaceSettingsPaths"];
    /** Add a watch path */
    post: operations["addSettingsPath"];
    parameters: {
      path: {
        kind: "movies" | "tv";
      };
    };
  };
  "/settings/paths/{kind}/{index}": {
    /** Remove a watch path */
    delete: operations["removeSettingsPath"];
  };
  "/settings/libraries/{kind}": {
    /** List library paths */
    get: operations["getSettingsLibraries"];
    /** Replace library paths */
    put: operations["replaceSettingsLibraries"];
    /** Add a library path */
    post: operations["addSettingsLibrary"];
    parameters: {
      path: {
        kind: "movies" | "tv";
      };
    };
  };
  "/settings/libraries/{kind}/{index}": {
    /** Remove a library path */
    delete: operations["removeSettingsLibrary"];
  };
  "/settings/sonarr/test": {
    /** Test Sonarr connection */
    post: operations["testSonarrConnection"];
  };
  "/settings/radarr/test": {
    /** Test Radarr connection */
    post: operations["testRadarrConnection"];
  };
  "/settings/jellyfin/test": {
    /** Test Jellyfin connection */
    post: operations["testJellyfinConnection"];
  };
  "/paths/preflight": {
    /** Check path access before saving */
    post: operations["preflightPath"];
  };
  "/daemon/status": {
    /** Daemon status */
    get: operations["getDaemonStatus"];
  };
  "/daemon/start": {
    /** Start the daemon process */
    post: operations["startDaemon"];
  };
  "/daemon/stop": {
    /** Request the daemon to stop */
    post: operations["stopDaemon"];
  };
  "/daemon/restart": {
    /** Stop then start the daemon */
    post: operations["restartDaemon"];
  };
  "/daemon/reload": {
    /** Reload daemon configuration */
    post: operations["reloadDaemon"];
  };
  "/daemon/recover": {
    /** Apply recovery action to an interrupted op */
    post: operations["recoverDaemon"];
  };
  "/database/rescan": {
    /** Kick off a full library rescan */
    post: operations["rescanDatabase"];
  };
  "/database/reset": {
    /** Reset the media database (typed-confirm gated) */
    post: operations["resetDatabase"];
  };
  "/events/op/{op_id}": {
    /** Server-Sent Events stream of frames for an op */
    get: operations["streamOpEvents"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    DashboardData: {
      libraryStats?: components["schemas"]["LibraryStats"];
      mediaManagers?: components["schemas"]["MediaManagerSummary"][];
      llmProvider?: components["schemas"]["LLMProviderSummary"];
      recentActivity?: components["schemas"]["ActivityEvent"][];
    };
    LibraryStats: {
      totalFiles?: number;
      /** Format: int64 */
      totalSize?: number;
      movieCount?: number;
      seriesCount?: number;
      episodeCount?: number;
      duplicateGroups?: number;
      /** Format: int64 */
      reclaimableBytes?: number;
      scatteredSeries?: number;
    };
    MediaManagerInfo: {
      id?: string;
      /** @enum {string} */
      type?: "sonarr" | "radarr" | "jellyfin" | "mediadownloader" | "custom";
      name?: string;
      enabled?: boolean;
      capabilities?: components["schemas"]["ManagerCapabilities"];
    };
    MediaManagerSummary: {
      id?: string;
      name?: string;
      type?: string;
      online?: boolean;
      queueSize?: number;
      stuckCount?: number;
    };
    ServiceStatus: {
      online?: boolean;
      version?: string;
      queueSize?: number;
      stuckCount?: number;
      error?: string;
    };
    ManagerCapabilities: {
      supportsRetry?: boolean;
      supportsPriority?: boolean;
      supportsHistory?: boolean;
      supportsQualityEdit?: boolean;
      supportsBulkActions?: boolean;
    };
    QueueItem: {
      /** Format: int64 */
      id?: number;
      title?: string;
      status?: string;
      progress?: number;
      /** Format: int64 */
      size?: number;
      /** Format: int64 */
      sizeRemaining?: number;
      timeLeft?: string;
      isStuck?: boolean;
      errorMessage?: string;
      downloadClient?: string;
    };
    LLMProviderInfo: {
      id?: string;
      /** @enum {string} */
      type?: "ollama" | "openai" | "anthropic" | "lmstudio" | "custom";
      name?: string;
      enabled?: boolean;
      currentModel?: string;
      capabilities?: components["schemas"]["LLMCapabilities"];
    };
    LLMProviderSummary: {
      id?: string;
      name?: string;
      online?: boolean;
      currentModel?: string;
    };
    LLMProviderStatus: {
      online?: boolean;
      model?: string;
      modelList?: components["schemas"]["LLMModel"][];
      error?: string;
    };
    LLMModel: {
      id?: string;
      name?: string;
      size?: string;
    };
    LLMCapabilities: {
      supportsStreaming?: boolean;
      supportsVision?: boolean;
      supportsModelSwitch?: boolean;
      localOnly?: boolean;
    };
    AISettings: {
      enabled?: boolean;
      defaultProvider?: string;
      confidenceThreshold?: number;
      autoApply?: boolean;
    };
    ActivityEvent: {
      id?: string;
      /** @enum {string} */
      type?: "FILE_DETECTED" | "FILE_ORGANIZED" | "DUPLICATE_FOUND" | "SYNC_COMPLETED" | "ERROR";
      message?: string;
      /** Format: date-time */
      timestamp?: string;
    };
    DuplicateAnalysis: {
      groups?: components["schemas"]["DuplicateGroup"][];
      totalFiles?: number;
      totalGroups?: number;
      /** Format: int64 */
      reclaimableBytes?: number;
    };
    DuplicateGroup: {
      id?: string;
      title?: string;
      year?: number;
      /** @enum {string} */
      mediaType?: "movie" | "series";
      files?: components["schemas"]["MediaFile"][];
      /** Format: int64 */
      bestFileId?: number;
      /** Format: int64 */
      reclaimableBytes?: number;
    };
    MediaFile: {
      /** Format: int64 */
      id?: number;
      path?: string;
      /** Format: int64 */
      size?: number;
      resolution?: string;
      sourceType?: string;
      qualityScore?: number;
    };
    ScatteredAnalysis: {
      items?: components["schemas"]["ScatteredItem"][];
      totalItems?: number;
      totalMoves?: number;
      /** Format: int64 */
      totalBytes?: number;
    };
    ScatteredItem: {
      /** Format: int64 */
      id?: number;
      title?: string;
      year?: number;
      mediaType?: string;
      locations?: string[];
      targetLocation?: string;
      filesToMove?: number;
      /** Format: int64 */
      bytesToMove?: number;
    };
    ConsolidationResult: {
      success?: boolean;
      filesMoved?: number;
      /** Format: int64 */
      bytesMoved?: number;
      errors?: string[];
    };
    ScanStatus: {
      /** @enum {string} */
      status?: "idle" | "scanning" | "completed" | "failed";
      progress?: number;
      message?: string;
    };
    AuthStatus: {
      enabled?: boolean;
      authenticated?: boolean;
    };
    OperationResult: {
      success?: boolean;
      message?: string;
      filesAffected?: number;
      /** Format: int64 */
      bytesAffected?: number;
    };
    Error: {
      code?: string;
      message?: string;
    };
    JellyfinVerificationStatus: {
      enabled?: boolean;
      pluginEnabled?: boolean;
      connected?: boolean;
      /** Format: date-time */
      lastVerification?: string;
      librariesVerified?: number;
      totalMismatches?: number;
    };
    JellyfinVerificationResult: {
      libraryPath?: string;
      scannedCount?: number;
      identifiedCount?: number;
      unidentifiedCount?: number;
      mismatches?: components["schemas"]["JellyfinMismatch"][];
      /** Format: date-time */
      lastRun?: string;
    };
    JellyfinMismatch: {
      path?: string;
      /** @enum {string} */
      issue?: "orphaned" | "missing" | "unidentified";
      itemName?: string;
      itemId?: string;
    };
    UnidentifiableItem: {
      id?: string;
      name?: string;
      path?: string;
      type?: string;
      /** Format: date-time */
      dateAdded?: string;
    };
    JellyfinPluginStatus: {
      installed?: boolean;
      version?: string;
      healthy?: boolean;
      libraries?: number;
      message?: string;
    };
    DaemonStatus: {
      /** @description One of running, stopped, starting, stopping, degraded */
      state?: string;
      pid?: number;
      uptime_seconds?: number;
      version?: string;
      [key: string]: unknown;
    };
    ReloadResult: {
      ok?: boolean;
      reloaded?: string[];
      failed?: {
          name?: string;
          error?: string;
        }[];
    };
    RecoverRequest: {
      /** @description Recovery action (e.g. discard) */
      action: string;
    };
    RescanRequest: {
      paths?: string[];
      dry_run?: boolean;
    };
    ResetRequest: {
      /** @description Must equal "media.db" to authorize the reset */
      confirm: string;
      preserve?: string[];
    };
    OpAccepted: {
      op_id: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /** Get dashboard aggregate data */
  getDashboard: {
    responses: {
      /** @description Dashboard data */
      200: {
        content: {
          "application/json": components["schemas"]["DashboardData"];
        };
      };
    };
  };
  /** List all configured media managers */
  listMediaManagers: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["MediaManagerInfo"][];
        };
      };
    };
  };
  /** Get service health and stats */
  getMediaManagerStatus: {
    parameters: {
      path: {
        managerId: string;
      };
    };
    responses: {
      /** @description Manager status */
      200: {
        content: {
          "application/json": components["schemas"]["ServiceStatus"];
        };
      };
    };
  };
  /** Get download queue */
  getMediaManagerQueue: {
    parameters: {
      query?: {
        limit?: number;
      };
      path: {
        managerId: string;
      };
    };
    responses: {
      /** @description Queue items */
      200: {
        content: {
          "application/json": components["schemas"]["QueueItem"][];
        };
      };
    };
  };
  /** Clear item from queue */
  clearQueueItem: {
    parameters: {
      query?: {
        blocklist?: boolean;
      };
      path: {
        managerId: string;
        itemId: number;
      };
    };
    responses: {
      /** @description Item cleared */
      200: {
        content: {
          "application/json": components["schemas"]["OperationResult"];
        };
      };
    };
  };
  /** Get stuck queue items */
  getStuckItems: {
    parameters: {
      path: {
        managerId: string;
      };
    };
    responses: {
      /** @description Stuck items */
      200: {
        content: {
          "application/json": components["schemas"]["QueueItem"][];
        };
      };
    };
  };
  /** Clear all stuck items */
  clearStuckItems: {
    parameters: {
      query?: {
        blocklist?: boolean;
      };
      path: {
        managerId: string;
      };
    };
    responses: {
      /** @description Items cleared */
      200: {
        content: {
          "application/json": components["schemas"]["OperationResult"];
        };
      };
    };
  };
  /** Trigger import scan */
  triggerManagerScan: {
    parameters: {
      path: {
        managerId: string;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          path?: string;
        };
      };
    };
    responses: {
      /** @description Scan triggered */
      202: {
        content: {
          "application/json": components["schemas"]["OperationResult"];
        };
      };
    };
  };
  /** List configured LLM providers */
  listLLMProviders: {
    responses: {
      /** @description List of providers */
      200: {
        content: {
          "application/json": components["schemas"]["LLMProviderInfo"][];
        };
      };
    };
  };
  /** Get provider health and model */
  getLLMProviderStatus: {
    parameters: {
      path: {
        providerId: string;
      };
    };
    responses: {
      /** @description Provider status */
      200: {
        content: {
          "application/json": components["schemas"]["LLMProviderStatus"];
        };
      };
    };
  };
  /** Get current AI settings */
  getAISettings: {
    responses: {
      /** @description AI settings */
      200: {
        content: {
          "application/json": components["schemas"]["AISettings"];
        };
      };
    };
  };
  /** Get paginated activity log */
  getActivity: {
    parameters: {
      query?: {
        limit?: number;
      };
    };
    responses: {
      /** @description Activity events */
      200: {
        content: {
          "application/json": {
            events?: components["schemas"]["ActivityEvent"][];
          };
        };
      };
    };
  };
  /** SSE stream for real-time activity */
  activityStream: {
    responses: {
      /** @description Server-Sent Events stream */
      200: {
        content: {
          "text/event-stream": string;
        };
      };
    };
  };
  /** Get duplicate analysis */
  getDuplicates: {
    responses: {
      /** @description Duplicate analysis */
      200: {
        content: {
          "application/json": components["schemas"]["DuplicateAnalysis"];
        };
      };
    };
  };
  /** Delete inferior file from duplicate group */
  deleteDuplicate: {
    parameters: {
      query?: {
        fileId?: number;
      };
      path: {
        groupId: string;
      };
    };
    responses: {
      /** @description File deleted */
      200: {
        content: {
          "application/json": components["schemas"]["OperationResult"];
        };
      };
    };
  };
  /** Get scattered media analysis */
  getScattered: {
    responses: {
      /** @description Scattered analysis */
      200: {
        content: {
          "application/json": components["schemas"]["ScatteredAnalysis"];
        };
      };
    };
  };
  /** Consolidate scattered media item */
  consolidateItem: {
    parameters: {
      path: {
        itemId: number;
      };
    };
    requestBody?: {
      content: {
        "application/json": {
          /** @default false */
          dryRun?: boolean;
        };
      };
    };
    responses: {
      /** @description Consolidation result */
      200: {
        content: {
          "application/json": components["schemas"]["ConsolidationResult"];
        };
      };
    };
  };
  /** Trigger library scan */
  startScan: {
    responses: {
      /** @description Scan started */
      202: {
        content: {
          "application/json": components["schemas"]["ScanStatus"];
        };
      };
    };
  };
  /** Get scan status */
  getScanStatus: {
    responses: {
      /** @description Scan status */
      200: {
        content: {
          "application/json": components["schemas"]["ScanStatus"];
        };
      };
    };
  };
  /** SSE stream for scan progress */
  scanStream: {
    responses: {
      /** @description Server-Sent Events stream */
      200: {
        content: {
          "text/event-stream": string;
        };
      };
    };
  };
  /** Check if auth is enabled and current state */
  getAuthStatus: {
    responses: {
      /** @description Auth status */
      200: {
        content: {
          "application/json": components["schemas"]["AuthStatus"];
        };
      };
    };
  };
  /** Authenticate with password */
  login: {
    requestBody?: {
      content: {
        "application/json": {
          password: string;
        };
      };
    };
    responses: {
      /** @description Login successful */
      200: {
        content: never;
      };
      /** @description Invalid password */
      401: {
        content: never;
      };
    };
  };
  /** Clear session cookie */
  logout: {
    responses: {
      /** @description Logged out */
      200: {
        content: never;
      };
    };
  };
  /** Get Jellyfin verification status */
  getJellyfinVerification: {
    responses: {
      /** @description Verification status */
      200: {
        content: {
          "application/json": components["schemas"]["JellyfinVerificationStatus"];
        };
      };
    };
  };
  /** Run Jellyfin verification for a library */
  runJellyfinVerification: {
    requestBody?: {
      content: {
        "application/json": {
          libraryId?: string;
          libraryPath?: string;
        };
      };
    };
    responses: {
      /** @description Verification started */
      202: {
        content: {
          "application/json": components["schemas"]["OperationResult"];
        };
      };
    };
  };
  /** Get verification results */
  getJellyfinVerificationResults: {
    parameters: {
      query?: {
        libraryId?: string;
      };
    };
    responses: {
      /** @description Verification results */
      200: {
        content: {
          "application/json": components["schemas"]["JellyfinVerificationResult"];
        };
      };
    };
  };
  /** Get unidentifiable items from Jellyfin */
  getJellyfinUnidentifiableItems: {
    parameters: {
      query?: {
        libraryId?: string;
      };
    };
    responses: {
      /** @description Unidentifiable items */
      200: {
        content: {
          "application/json": components["schemas"]["UnidentifiableItem"][];
        };
      };
    };
  };
  /** Get JellyWatch companion plugin status */
  getJellyfinPluginStatus: {
    responses: {
      /** @description Plugin status */
      200: {
        content: {
          "application/json": components["schemas"]["JellyfinPluginStatus"];
        };
      };
    };
  };
  /** Health check endpoint */
  healthCheck: {
    responses: {
      /** @description Service is healthy */
      200: {
        content: {
          "application/json": {
            status?: string;
            version?: string;
          };
        };
      };
    };
  };
  /** Receive Jellyfin webhook events */
  jellyfinWebhook: {
    requestBody: {
      content: {
        "application/json": {
          [key: string]: unknown;
        };
      };
    };
    responses: {
      /** @description Event accepted */
      200: {
        content: never;
      };
      /** @description Invalid payload */
      400: {
        content: never;
      };
      /** @description Invalid or missing webhook secret */
      401: {
        content: never;
      };
    };
  };
  /** Read a config section */
  getSettingsSection: {
    parameters: {
      query?: {
        reveal?: 1;
      };
      path: {
        section: string;
      };
    };
    responses: {
      /** @description Config section */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
      /** @description Unknown section */
      404: {
        content: never;
      };
    };
  };
  /** Replace a config section */
  putSettingsSection: {
    parameters: {
      path: {
        section: string;
      };
    };
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Saved */
      200: {
        content: {
          "application/json": Record<string, never>;
        };
      };
    };
  };
  /** List watch paths */
  getSettingsPaths: {
    parameters: {
      path: {
        kind: "movies" | "tv";
      };
    };
    responses: {
      /** @description Watch paths */
      200: {
        content: never;
      };
    };
  };
  /** Replace watch paths */
  replaceSettingsPaths: {
    parameters: {
      path: {
        kind: "movies" | "tv";
      };
    };
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Replaced */
      200: {
        content: never;
      };
    };
  };
  /** Add a watch path */
  addSettingsPath: {
    parameters: {
      path: {
        kind: "movies" | "tv";
      };
    };
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Added */
      201: {
        content: never;
      };
    };
  };
  /** Remove a watch path */
  removeSettingsPath: {
    parameters: {
      path: {
        kind: "movies" | "tv";
        index: number;
      };
    };
    responses: {
      /** @description Removed */
      204: {
        content: never;
      };
    };
  };
  /** List library paths */
  getSettingsLibraries: {
    parameters: {
      path: {
        kind: "movies" | "tv";
      };
    };
    responses: {
      /** @description Library paths */
      200: {
        content: never;
      };
    };
  };
  /** Replace library paths */
  replaceSettingsLibraries: {
    parameters: {
      path: {
        kind: "movies" | "tv";
      };
    };
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Replaced */
      200: {
        content: never;
      };
    };
  };
  /** Add a library path */
  addSettingsLibrary: {
    parameters: {
      path: {
        kind: "movies" | "tv";
      };
    };
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Added */
      201: {
        content: never;
      };
    };
  };
  /** Remove a library path */
  removeSettingsLibrary: {
    parameters: {
      path: {
        kind: "movies" | "tv";
        index: number;
      };
    };
    responses: {
      /** @description Removed */
      204: {
        content: never;
      };
    };
  };
  /** Test Sonarr connection */
  testSonarrConnection: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Connection test result */
      200: {
        content: never;
      };
    };
  };
  /** Test Radarr connection */
  testRadarrConnection: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Connection test result */
      200: {
        content: never;
      };
    };
  };
  /** Test Jellyfin connection */
  testJellyfinConnection: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Connection test result */
      200: {
        content: never;
      };
    };
  };
  /** Check path access before saving */
  preflightPath: {
    requestBody: {
      content: {
        "application/json": Record<string, never>;
      };
    };
    responses: {
      /** @description Probe result */
      200: {
        content: never;
      };
    };
  };
  /** Daemon status */
  getDaemonStatus: {
    responses: {
      /** @description Daemon status */
      200: {
        content: {
          "application/json": components["schemas"]["DaemonStatus"];
        };
      };
    };
  };
  /** Start the daemon process */
  startDaemon: {
    responses: {
      /** @description Start requested */
      202: {
        content: never;
      };
      /** @description Launcher error */
      500: {
        content: never;
      };
    };
  };
  /** Request the daemon to stop */
  stopDaemon: {
    responses: {
      /** @description Stop requested */
      202: {
        content: never;
      };
      /** @description IPC error */
      502: {
        content: never;
      };
    };
  };
  /** Stop then start the daemon */
  restartDaemon: {
    responses: {
      /** @description Restart requested */
      202: {
        content: never;
      };
      /** @description Launcher error */
      500: {
        content: never;
      };
    };
  };
  /** Reload daemon configuration */
  reloadDaemon: {
    responses: {
      /** @description Reload result */
      200: {
        content: {
          "application/json": components["schemas"]["ReloadResult"];
        };
      };
      /** @description IPC error */
      502: {
        content: never;
      };
    };
  };
  /** Apply recovery action to an interrupted op */
  recoverDaemon: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RecoverRequest"];
      };
    };
    responses: {
      /** @description Recovery applied */
      200: {
        content: {
          "application/json": {
            [key: string]: unknown;
          };
        };
      };
      /** @description IPC error */
      502: {
        content: never;
      };
    };
  };
  /** Kick off a full library rescan */
  rescanDatabase: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["RescanRequest"];
      };
    };
    responses: {
      /** @description Op started */
      202: {
        content: {
          "application/json": components["schemas"]["OpAccepted"];
        };
      };
    };
  };
  /** Reset the media database (typed-confirm gated) */
  resetDatabase: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetRequest"];
      };
    };
    responses: {
      /** @description Op started */
      202: {
        content: {
          "application/json": components["schemas"]["OpAccepted"];
        };
      };
      /** @description Confirmation token missing or wrong */
      400: {
        content: never;
      };
    };
  };
  /** Server-Sent Events stream of frames for an op */
  streamOpEvents: {
    parameters: {
      path: {
        op_id: string;
      };
    };
    responses: {
      /** @description SSE stream of progress / done / error frames */
      200: {
        content: {
          "text/event-stream": string;
        };
      };
      /** @description No such op */
      404: {
        content: never;
      };
    };
  };
}
