// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get paginated activity log
	// (GET /activity)
	GetActivity(w http.ResponseWriter, r *http.Request, params GetActivityParams)
	// SSE stream for real-time activity
	// (GET /activity/stream)
	ActivityStream(w http.ResponseWriter, r *http.Request)
	// Get current AI settings
	// (GET /ai/settings)
	GetAISettings(w http.ResponseWriter, r *http.Request)
	// Authenticate with password
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Clear session cookie
	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Check if auth is enabled and current state
	// (GET /auth/status)
	GetAuthStatus(w http.ResponseWriter, r *http.Request)
	// Get dashboard aggregate data
	// (GET /dashboard)
	GetDashboard(w http.ResponseWriter, r *http.Request)
	// Get duplicate analysis
	// (GET /duplicates)
	GetDuplicates(w http.ResponseWriter, r *http.Request)
	// Delete inferior file from duplicate group
	// (DELETE /duplicates/{groupId})
	DeleteDuplicate(w http.ResponseWriter, r *http.Request, groupId string, params DeleteDuplicateParams)
	// Health check endpoint
	// (GET /health)
	HealthCheck(w http.ResponseWriter, r *http.Request)
	// List configured LLM providers
	// (GET /llm-providers)
	ListLLMProviders(w http.ResponseWriter, r *http.Request)
	// Get provider health and model
	// (GET /llm-providers/{providerId}/status)
	GetLLMProviderStatus(w http.ResponseWriter, r *http.Request, providerId string)
	// List all configured media managers
	// (GET /media-managers)
	ListMediaManagers(w http.ResponseWriter, r *http.Request)
	// Get download queue
	// (GET /media-managers/{managerId}/queue)
	GetMediaManagerQueue(w http.ResponseWriter, r *http.Request, managerId string, params GetMediaManagerQueueParams)
	// Clear item from queue
	// (DELETE /media-managers/{managerId}/queue/{itemId})
	ClearQueueItem(w http.ResponseWriter, r *http.Request, managerId string, itemId int64, params ClearQueueItemParams)
	// Trigger import scan
	// (POST /media-managers/{managerId}/scan)
	TriggerManagerScan(w http.ResponseWriter, r *http.Request, managerId string)
	// Get service health and stats
	// (GET /media-managers/{managerId}/status)
	GetMediaManagerStatus(w http.ResponseWriter, r *http.Request, managerId string)
	// Clear all stuck items
	// (DELETE /media-managers/{managerId}/stuck)
	ClearStuckItems(w http.ResponseWriter, r *http.Request, managerId string, params ClearStuckItemsParams)
	// Get stuck queue items
	// (GET /media-managers/{managerId}/stuck)
	GetStuckItems(w http.ResponseWriter, r *http.Request, managerId string)
	// Trigger library scan
	// (POST /scan)
	StartScan(w http.ResponseWriter, r *http.Request)
	// Get scan status
	// (GET /scan/status)
	GetScanStatus(w http.ResponseWriter, r *http.Request)
	// SSE stream for scan progress
	// (GET /scan/stream)
	ScanStream(w http.ResponseWriter, r *http.Request)
	// Get scattered media analysis
	// (GET /scattered)
	GetScattered(w http.ResponseWriter, r *http.Request)
	// Consolidate scattered media item
	// (POST /scattered/{itemId}/consolidate)
	ConsolidateItem(w http.ResponseWriter, r *http.Request, itemId int64)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get paginated activity log
// (GET /activity)
func (_ Unimplemented) GetActivity(w http.ResponseWriter, r *http.Request, params GetActivityParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SSE stream for real-time activity
// (GET /activity/stream)
func (_ Unimplemented) ActivityStream(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current AI settings
// (GET /ai/settings)
func (_ Unimplemented) GetAISettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Authenticate with password
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Clear session cookie
// (POST /auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Check if auth is enabled and current state
// (GET /auth/status)
func (_ Unimplemented) GetAuthStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get dashboard aggregate data
// (GET /dashboard)
func (_ Unimplemented) GetDashboard(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get duplicate analysis
// (GET /duplicates)
func (_ Unimplemented) GetDuplicates(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Delete inferior file from duplicate group
// (DELETE /duplicates/{groupId})
func (_ Unimplemented) DeleteDuplicate(w http.ResponseWriter, r *http.Request, groupId string, params DeleteDuplicateParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check endpoint
// (GET /health)
func (_ Unimplemented) HealthCheck(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List configured LLM providers
// (GET /llm-providers)
func (_ Unimplemented) ListLLMProviders(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get provider health and model
// (GET /llm-providers/{providerId}/status)
func (_ Unimplemented) GetLLMProviderStatus(w http.ResponseWriter, r *http.Request, providerId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all configured media managers
// (GET /media-managers)
func (_ Unimplemented) ListMediaManagers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get download queue
// (GET /media-managers/{managerId}/queue)
func (_ Unimplemented) GetMediaManagerQueue(w http.ResponseWriter, r *http.Request, managerId string, params GetMediaManagerQueueParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Clear item from queue
// (DELETE /media-managers/{managerId}/queue/{itemId})
func (_ Unimplemented) ClearQueueItem(w http.ResponseWriter, r *http.Request, managerId string, itemId int64, params ClearQueueItemParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Trigger import scan
// (POST /media-managers/{managerId}/scan)
func (_ Unimplemented) TriggerManagerScan(w http.ResponseWriter, r *http.Request, managerId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get service health and stats
// (GET /media-managers/{managerId}/status)
func (_ Unimplemented) GetMediaManagerStatus(w http.ResponseWriter, r *http.Request, managerId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Clear all stuck items
// (DELETE /media-managers/{managerId}/stuck)
func (_ Unimplemented) ClearStuckItems(w http.ResponseWriter, r *http.Request, managerId string, params ClearStuckItemsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get stuck queue items
// (GET /media-managers/{managerId}/stuck)
func (_ Unimplemented) GetStuckItems(w http.ResponseWriter, r *http.Request, managerId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Trigger library scan
// (POST /scan)
func (_ Unimplemented) StartScan(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get scan status
// (GET /scan/status)
func (_ Unimplemented) GetScanStatus(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// SSE stream for scan progress
// (GET /scan/stream)
func (_ Unimplemented) ScanStream(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get scattered media analysis
// (GET /scattered)
func (_ Unimplemented) GetScattered(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Consolidate scattered media item
// (POST /scattered/{itemId}/consolidate)
func (_ Unimplemented) ConsolidateItem(w http.ResponseWriter, r *http.Request, itemId int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetActivity operation middleware
func (siw *ServerInterfaceWrapper) GetActivity(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetActivityParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetActivity(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ActivityStream operation middleware
func (siw *ServerInterfaceWrapper) ActivityStream(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ActivityStream(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAISettings operation middleware
func (siw *ServerInterfaceWrapper) GetAISettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAISettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetAuthStatus operation middleware
func (siw *ServerInterfaceWrapper) GetAuthStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetAuthStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDashboard operation middleware
func (siw *ServerInterfaceWrapper) GetDashboard(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDashboard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDuplicates operation middleware
func (siw *ServerInterfaceWrapper) GetDuplicates(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDuplicates(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDuplicate operation middleware
func (siw *ServerInterfaceWrapper) DeleteDuplicate(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "groupId" -------------
	var groupId string

	err = runtime.BindStyledParameterWithOptions("simple", "groupId", chi.URLParam(r, "groupId"), &groupId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "groupId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params DeleteDuplicateParams

	// ------------- Optional query parameter "fileId" -------------

	err = runtime.BindQueryParameter("form", true, false, "fileId", r.URL.Query(), &params.FileId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "fileId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDuplicate(w, r, groupId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// HealthCheck operation middleware
func (siw *ServerInterfaceWrapper) HealthCheck(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.HealthCheck(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListLLMProviders operation middleware
func (siw *ServerInterfaceWrapper) ListLLMProviders(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListLLMProviders(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLLMProviderStatus operation middleware
func (siw *ServerInterfaceWrapper) GetLLMProviderStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "providerId" -------------
	var providerId string

	err = runtime.BindStyledParameterWithOptions("simple", "providerId", chi.URLParam(r, "providerId"), &providerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "providerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLLMProviderStatus(w, r, providerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMediaManagers operation middleware
func (siw *ServerInterfaceWrapper) ListMediaManagers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMediaManagers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMediaManagerQueue operation middleware
func (siw *ServerInterfaceWrapper) GetMediaManagerQueue(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "managerId" -------------
	var managerId string

	err = runtime.BindStyledParameterWithOptions("simple", "managerId", chi.URLParam(r, "managerId"), &managerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "managerId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetMediaManagerQueueParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMediaManagerQueue(w, r, managerId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClearQueueItem operation middleware
func (siw *ServerInterfaceWrapper) ClearQueueItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "managerId" -------------
	var managerId string

	err = runtime.BindStyledParameterWithOptions("simple", "managerId", chi.URLParam(r, "managerId"), &managerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "managerId", Err: err})
		return
	}

	// ------------- Path parameter "itemId" -------------
	var itemId int64

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ClearQueueItemParams

	// ------------- Optional query parameter "blocklist" -------------

	err = runtime.BindQueryParameter("form", true, false, "blocklist", r.URL.Query(), &params.Blocklist)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "blocklist", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearQueueItem(w, r, managerId, itemId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TriggerManagerScan operation middleware
func (siw *ServerInterfaceWrapper) TriggerManagerScan(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "managerId" -------------
	var managerId string

	err = runtime.BindStyledParameterWithOptions("simple", "managerId", chi.URLParam(r, "managerId"), &managerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "managerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TriggerManagerScan(w, r, managerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMediaManagerStatus operation middleware
func (siw *ServerInterfaceWrapper) GetMediaManagerStatus(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "managerId" -------------
	var managerId string

	err = runtime.BindStyledParameterWithOptions("simple", "managerId", chi.URLParam(r, "managerId"), &managerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "managerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMediaManagerStatus(w, r, managerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ClearStuckItems operation middleware
func (siw *ServerInterfaceWrapper) ClearStuckItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "managerId" -------------
	var managerId string

	err = runtime.BindStyledParameterWithOptions("simple", "managerId", chi.URLParam(r, "managerId"), &managerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "managerId", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ClearStuckItemsParams

	// ------------- Optional query parameter "blocklist" -------------

	err = runtime.BindQueryParameter("form", true, false, "blocklist", r.URL.Query(), &params.Blocklist)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "blocklist", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ClearStuckItems(w, r, managerId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStuckItems operation middleware
func (siw *ServerInterfaceWrapper) GetStuckItems(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "managerId" -------------
	var managerId string

	err = runtime.BindStyledParameterWithOptions("simple", "managerId", chi.URLParam(r, "managerId"), &managerId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "managerId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStuckItems(w, r, managerId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StartScan operation middleware
func (siw *ServerInterfaceWrapper) StartScan(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StartScan(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScanStatus operation middleware
func (siw *ServerInterfaceWrapper) GetScanStatus(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScanStatus(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ScanStream operation middleware
func (siw *ServerInterfaceWrapper) ScanStream(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ScanStream(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScattered operation middleware
func (siw *ServerInterfaceWrapper) GetScattered(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScattered(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConsolidateItem operation middleware
func (siw *ServerInterfaceWrapper) ConsolidateItem(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "itemId" -------------
	var itemId int64

	err = runtime.BindStyledParameterWithOptions("simple", "itemId", chi.URLParam(r, "itemId"), &itemId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "itemId", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConsolidateItem(w, r, itemId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/activity", wrapper.GetActivity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/activity/stream", wrapper.ActivityStream)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ai/settings", wrapper.GetAISettings)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/auth/status", wrapper.GetAuthStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/dashboard", wrapper.GetDashboard)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/duplicates", wrapper.GetDuplicates)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/duplicates/{groupId}", wrapper.DeleteDuplicate)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/health", wrapper.HealthCheck)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/llm-providers", wrapper.ListLLMProviders)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/llm-providers/{providerId}/status", wrapper.GetLLMProviderStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/media-managers", wrapper.ListMediaManagers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/media-managers/{managerId}/queue", wrapper.GetMediaManagerQueue)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/media-managers/{managerId}/queue/{itemId}", wrapper.ClearQueueItem)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/media-managers/{managerId}/scan", wrapper.TriggerManagerScan)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/media-managers/{managerId}/status", wrapper.GetMediaManagerStatus)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/media-managers/{managerId}/stuck", wrapper.ClearStuckItems)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/media-managers/{managerId}/stuck", wrapper.GetStuckItems)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/scan", wrapper.StartScan)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/scan/status", wrapper.GetScanStatus)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/scan/stream", wrapper.ScanStream)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/scattered", wrapper.GetScattered)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/scattered/{itemId}/consolidate", wrapper.ConsolidateItem)
	})

	return r
}
