// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"time"
)

// Defines values for DuplicateGroupMediaType.
const (
	Movie  DuplicateGroupMediaType = "movie"
	Series DuplicateGroupMediaType = "series"
)

// Defines values for ScanProgressType.
const (
	ScanProgressTypeCompleted ScanProgressType = "completed"
	ScanProgressTypeError     ScanProgressType = "error"
	ScanProgressTypeProgress  ScanProgressType = "progress"
	ScanProgressTypeStarted   ScanProgressType = "started"
)

// Defines values for ScanStatusStatus.
const (
	ScanStatusStatusCompleted ScanStatusStatus = "completed"
	ScanStatusStatusFailed    ScanStatusStatus = "failed"
	ScanStatusStatusIdle      ScanStatusStatus = "idle"
	ScanStatusStatusScanning  ScanStatusStatus = "scanning"
)

// DuplicateAnalysis defines model for DuplicateAnalysis.
type DuplicateAnalysis struct {
	Groups           []DuplicateGroup `json:"groups"`
	ReclaimableBytes int64            `json:"reclaimableBytes"`
	TotalFiles       int              `json:"totalFiles"`
	TotalGroups      int              `json:"totalGroups"`
}

// DuplicateGroup defines model for DuplicateGroup.
type DuplicateGroup struct {
	BestFileId       int64                   `json:"bestFileId"`
	Episode          *int                    `json:"episode"`
	Files            []MediaFile             `json:"files"`
	Id               string                  `json:"id"`
	MediaType        DuplicateGroupMediaType `json:"mediaType"`
	ReclaimableBytes int64                   `json:"reclaimableBytes"`
	Season           *int                    `json:"season"`
	Title            string                  `json:"title"`
	Year             *int                    `json:"year"`
}

// DuplicateGroupMediaType defines model for DuplicateGroup.MediaType.
type DuplicateGroupMediaType string

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// MediaFile defines model for MediaFile.
type MediaFile struct {
	Id           int64   `json:"id"`
	Path         string  `json:"path"`
	QualityScore int     `json:"qualityScore"`
	Resolution   *string `json:"resolution,omitempty"`
	Size         int64   `json:"size"`
	SourceType   *string `json:"sourceType,omitempty"`
}

// OperationResult defines model for OperationResult.
type OperationResult struct {
	BytesAffected *int64  `json:"bytesAffected,omitempty"`
	Error         *string `json:"error,omitempty"`
	FilesAffected *int    `json:"filesAffected,omitempty"`
	Message       *string `json:"message,omitempty"`
	Success       bool    `json:"success"`
}

// ScanProgress defines model for ScanProgress.
type ScanProgress struct {
	Current         *int              `json:"current,omitempty"`
	DuplicatesFound *int              `json:"duplicatesFound,omitempty"`
	Message         *string           `json:"message,omitempty"`
	ScatteredFound  *int              `json:"scatteredFound,omitempty"`
	Total           *int              `json:"total,omitempty"`
	Type            *ScanProgressType `json:"type,omitempty"`
}

// ScanProgressType defines model for ScanProgress.Type.
type ScanProgressType string

// ScanStatus defines model for ScanStatus.
type ScanStatus struct {
	CompletedAt *time.Time       `json:"completedAt,omitempty"`
	Message     *string          `json:"message,omitempty"`
	Progress    *int             `json:"progress,omitempty"`
	StartedAt   *time.Time       `json:"startedAt,omitempty"`
	Status      ScanStatusStatus `json:"status"`
}

// ScanStatusStatus defines model for ScanStatus.Status.
type ScanStatusStatus string

// ScatteredAnalysis defines model for ScatteredAnalysis.
type ScatteredAnalysis struct {
	Items      []ScatteredItem `json:"items"`
	TotalBytes int64           `json:"totalBytes"`
	TotalItems int             `json:"totalItems"`
	TotalMoves int             `json:"totalMoves"`
}

// ScatteredItem defines model for ScatteredItem.
type ScatteredItem struct {
	BytesToMove    *int64   `json:"bytesToMove,omitempty"`
	FilesToMove    int      `json:"filesToMove"`
	Id             int64    `json:"id"`
	Locations      []string `json:"locations"`
	MediaType      string   `json:"mediaType"`
	TargetLocation string   `json:"targetLocation"`
	Title          string   `json:"title"`
	Year           *int     `json:"year"`
}

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// DeleteDuplicateParams defines parameters for DeleteDuplicate.
type DeleteDuplicateParams struct {
	// FileId Specific file to delete (default is auto-selected inferior)
	FileId *int64 `form:"fileId,omitempty" json:"fileId,omitempty"`
}
